Presentation.Website/Controllers/SipController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using MarcinWork.Sip.Domain.Interfaces;
using Microsoft.AspNetCore.Mvc;
using MarcinWork.Sip.Presentation.Website.Models;
using System.Security.Claims;

namespace MarcinWork.Sip.Presentation.Website.Controllers
{
    public class SipController : Controller
    {
        public IActionResult Stop(string stopCode)
        {
            return View();
        }

        public IActionResult LiveSchedule(string stopCode)
        {
            return PartialView("_LiveSchedule");
        }

        public IActionResult Search()
        {
            return View();
        }

        public IActionResult SearchLines()
        {
            return PartialView("_SearchLines");
        }

        public IActionResult SearchRoutes(int lineId)
        {
            return PartialView("_SearchRoutes");
        }

        public IActionResult SearchMap(decimal longMin, decimal longMax, decimal latMin, decimal latMax)
        {
            return PartialView("_SearchMap");
        }
        
        public IActionResult MyStops()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

Presentation.Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>MW SIP</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/leaflet/leaflet.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/lib/leaflet/leaflet.css" asp-append-version="true" />
    </environment>
</head>
<body>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/leaflet/leaflet.js"></script>
        <script src="~/lib/leaflet/leaflet.uGeoJSON.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/lib/leaflet/leaflet.js" asp-append-version="true"></script>
        <script src="~/lib/leaflet/leaflet.uGeoJSON.js" asp-append-version="true"></script>
    </environment>

    <script>
        $(document).ready(function () {
            $.ajaxSetup({ 'global': true });

            $(document).ajaxStart(function () {
                $('#ajaxWaiting').show();
            });

            $(document).ajaxStop(function () {
                $('#ajaxWaiting').hide();
            });
        });
    </script>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MW SIP</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Sip" asp-action="Search">Wyszukaj</a></li>
                    <li><a disabled asp-area="" asp-controller="Sip" asp-action="MyStops">Moje przystanki</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - MW SIP</p>
        </footer>
    </div>

    @RenderSection("Scripts", required: false)

    <div class="progress-bar progress-bar-success progress-bar-striped active" hidden="hidden" id="ajaxWaiting" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%; position: fixed; bottom: 0; left: 0; height: 12px; margin: 0;" />
</body>
</html>